version: '3.9'
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - SECRET_KEY=changeme
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/habrio
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: habrio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
