"""Testing first time

Revision ID: 055cb63f2358
Revises: db3ea466a6e0
Create Date: 2025-07-30 05:26:33.617267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055cb63f2358'
down_revision = 'db3ea466a6e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumer_wallet', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_phone'])

    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=64), nullable=True))

    with op.batch_alter_table('vendor_wallet', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_wallet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.drop_column('token')

    with op.batch_alter_table('consumer_wallet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
