name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov
    - name: Run tests with coverage
      run: pytest --cov=app --cov=agent --cov=models --cov=extensions --cov-report=term-missing --cov-fail-under=90
    - name: Build Docker image
      run: docker build -t habrio:ci .
